#!/usr/bin/env bash
#Display subdomains for a domain

get_record_info() {
    domain=$1
    subdomain=$2
    result=$(dig +short $subdomain.$domain)
    if [[ ! -z "$result" ]]; then
	echo "The subdomain $subdomain is a record and points to $result"
    fi
}

domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
    for s in www lb-01 web-01 web-02; do
	get_record_info $domain $s
    done
else
    get_record_info $domain $subdomain
fi
