#!/usr/bin/env bash
#Display subdomains for a domain

function dig_record_info() {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | awk -F' ' '/^;; ANSWER SECTION:/ {print $1"\n"$2"\n"$3"\n"$4}'
}

if [ $# -eq 1 ]; then
	dig_record_info www "$1"
	dig_record_info lb-01 "$1"
	dig_record_info web-01 "$1"
	dig_record_info web-02 "$1"
elif [ $# -eq 2 ]; then
    	dig_record_info "$2" "$1"
else
	echo "Usage: $(basename "$0") <domain> [subdomain]" >&2
	exit 1
fi
