#!/usr/bin/env bash
#Update package lists
sudo apt-get -y update

#Install Nginx
sudo apt-get -y install nginx

sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
#Start Nginx
sudo service nginx start
