#!/usr/bin/env bash
# Configure Nginx server to add a custom Nginx response header.

#Update package
sudo apt-get -y update
sudo apt-get -y install nginx

HOSTNAME=$(hostname)

sudo sed -i "/listen \[::\]:80 default_server;/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo systemctl restart nginx
