#!/usr/bin/env bash
#This script installs and configures HAProxy to balance the load between web-01 and web-02

#Update the package
sudo apt-get update

sudo apt-get install -y haproxy

sudo systemctl enable haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

cat << EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client 5000ms
    timeout server 5000ms

frontend http_back
    balance roundrobin
    server web-01 373950-web-01:80 check
    server web-02 373950-web-02:80 check
EOF

sudo systemctl restart haproxy
