#!/usr/bin/env bash
# This script runs Nginx as Nginx
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/listen 80;/listen 8080;/" /etc/nginx/sites-available/default
if ! id "nginx" &>/dev/null; then
	sudo useradd -r -s /bin/false nginx
fi

sudo -u nginx service nginx restart
